apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: cluster
  namespace: default
spec:
  mon:
    # change: 3 -> 4
    count: 4
  mgr:
    count: 2
  storage:
    storageClassDeviceSets:
      - name: hdd
        count: 4
        volumeClaimTemplates:
          - metadata:
              name: data
        placement:
          tolerations:
            - key: hdd
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: topology.kubernetes.io/zone
              whenUnsatisfiable: ScheduleAnyway
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
      - name: ssd
        # change: 3 -> 5
        count: 5
        volumeClaimTemplates:
          - metadata:
              name: data
        placement:
          # add
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: ssd
                    operator: Exists
          tolerations:
            - key: ssd
          # change: maxSkew 1 -> 2, whenUnsatisfiable ScheduleAnyway -> DoNotSchedule
          topologySpreadConstraints:
            - maxSkew: 2
              topologyKey: topology.kubernetes.io/zone
              whenUnsatisfiable: DoNotSchedule
            - maxSkew: 2
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
